ci for check artifact update

diff --git a/.github/workflows/wasm-tests-full.yml b/.github/workflows/wasm-tests-full.yml
--- a/.github/workflows/wasm-tests-full.yml
+++ b/.github/workflows/wasm-tests-full.yml
@@ -13,6 +13,15 @@ jobs:
     - uses: actions/checkout@v4.1.0
     - name: Build optimised Wasm binaries
       run: "./scripts/optimizer.sh"
+    - name: Check if artifacts changed
+      run: |
+        if [ -n "$(git diff --stat artifacts/)" ]; then
+          echo "Error: Artifacts have changed after optimization"
+          echo "Please commit the latest contract to the artifacts/ directory"
+          exit 1
+        else
+          echo "Artifacts are unchanged"
+        fi
     - name: List optimised Wasm binaries
       run: bash -c "ls $WORKSPACE/artifacts/*.wasm"
     - name: Install cosmwasm-check
